# Site settings
title: I'm Izzy
description: "Though I do prefer being called Yi-Jirr. Currently a USC MBA Candidate for Class of '18."
url: 'https://alpaca-power.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Yi-Jirr Chen'
  email: yijirr.chen@protonmail.com
  twitter_username: yijirr
  facebook_username: yijirr.chen
  github_username:  alpaca-power
  linkedin_username: yijirr-chen

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
